### ISSUE TITLE
semver violation: v0.5.2->v0.5.3

### ISSUE THREAD

**Issue by glensc** [MarcusSchwarz/lesserphp#17]
v0.5.3 is absolutely [semver](https://semver.org/) incompatible with v0.5.2

```diff
             "autoload": {
-                "classmap": [
-                    "lessc.inc.php"
-                ]
+                "psr-4": {
+                    "LesserPhp\\": "src/LesserPhp/"
+                }
             },
```

please don't force people use exact versions in their composer.json if you have such broken versioning scheme!

example:
- https://travis-ci.org/mrclay/minify/jobs/626746825

```
...................S........PHP Fatal error:  Class 'lessc' not found in /home/travis/build/mrclay/minify/lib/Minify/LessCssSource.php on line 122
PHP Stack trace:
```

`0.5.3` must be nuked and released as `0.6.x`, or made backwards compatible with 
`0.5.2` release providing autoloader for `\lessc` class.

**Comment by phy25** [comment]
Looks like this is introduced by my PR #16. I felt a bit confused about the namespace when I submitted that PR until I realized now that `master` is totally different from `0.5.3` (DokuWiki is actually using the stable branch too, so we will need this to be fixed). Sorry about that!

@MarcusSchwarz Do you think that it helps if I submit another version of #16 to target `0.5.3` and you release a new minor version?

**Comment by MarcusSchwarz** [comment]
woah, f*
I did not pay attention that the master is in a so far off WIP state, I haven't been working on it quite some time.
I've created a new branch from 0.5.2, and added 7.4 support there. I also fixed a broken array access in lib_luma(); It is release as 0.5.4

I hope this fixes the problems introduced by my stupidity :(

**Comment by phy25** [comment]
@MarcusSchwarz Is there any reason that you skipped 3d95dec0dbc97ee9897b71effddb329a963103d0 in `0.5.3` for the new `0.5-dev` branch?

**Comment by MarcusSchwarz** [comment]
@phy25 I branched 0.5-dev from 0.5.2, the last working released version; I *guess* 0.5.3 was another WIP branch. I definitely have to do some cleanup here. I'm not working with less anymore, so the project is in some state of slumber :/

**Comment by phy25** [comment]
Also looks like they rely on composer (and this is why it happens automatically during an upgrade) but I don't see 0.5.4 there now (https://packagist.org/packages/marcusschwarz/lesserphp).

**Comment by MarcusSchwarz** [comment]
Thanks for letting me know. Seems like some access token was not valid anymore. I reauthorized packagist, it should be up to date again.

**Comment by glensc** [comment]
isn't the easy fix to add back classmap in composer?

```json
                "classmap": [
                    "lessc.inc.php"
                ]
```

**Comment by phy25** [comment]
@glensc I don't think the two branches are compatiable, or I should say I am not sure what change is introduced in master.

**Comment by glensc** [comment]
I see [v0.5.4] was released, so this issue is solved?

[v0.5.4]: https://github.com/MarcusSchwarz/lesserphp/releases/tag/v0.5.4

**Comment by phy25** [comment]
@glensc Yes there should be no more violations.

**Comment by glensc** [comment]
I did not verify result myself, also the 0.5.3 was not yanked. but i'm closing anyway as seems no more changes are planned.
